CC = gcc
CFLAGS = -std=gnu99 -Wall -Wextra -Werror -pedantic
LDFLAGS = -lrt -lpthread
PROJECT_NAME = proj2

$(PROJECT_NAME): $(PROJECT_NAME).c
	$(CC) $(CFLAGS) $(LDFLAGS) $(PROJECT_NAME).c -o $(PROJECT_NAME)
